#git
alias g='git'
alias ga='git add'
alias gaa='git add --all'
alias gb='git branch'
alias gbd='git branch -d'
alias gca='git commit -a'
alias gcb='git checkout -b'
alias gcl='git clone --recurse-modules'
alias gclean='git reset --hard && git clean -dfxx'
alias gco='git checkout'
alias gd='git diff'
alias gf='git fetch'
alias gfo='git fetch origin'
alias gpl='git pull'
alias gm='git merge'
alias gp='git push'
alias gs='git status'
alias gt='git tag'
alias gptf='git push --follow-tags'

